### ISSUE TITLE
Dirt decals are projected on a chair when the chair rolls over them.

### ISSUE THREAD

**Issue by Meisaka** [techcompliant/TC#26]
Only some of the dirt does this I think.

**Comment by paultech** [comment]
The decal system in UE4 is wanting in the ability to select decal channels. Right now the only options are objects to 'receive decals' or not. 

The likely best solutions is the convert the current decal dirt over to the wear material functions to place the dirt/muck as part of the material instead of the lighting pass.

Will mark the chair as no-receive decals for time being as we rework this.

**Comment by paultech** [comment]
Chairs no longer receive decals.
